# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: 'MONGO_DB'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectuser
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports: 
      - 27017:27017
    volumes: 
      - ${PWD}/scripts/mongodb:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: projectuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123