# Use root/example as user/password credentials
version: '3.1'

services:

  # server:
  #   container_name: NEST_APP
  #   command: npm run start:dev
  #   build: .
  #   ports:
  #     - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - db-compose-network

  mongo:
    container_name: 'MONGO_DB'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectuser
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports: 
      - 27017:27017
    volumes: 
      - ${PWD}/scripts/mongodb:/docker-entrypoint-initdb.d/
    networks:
      - db-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: projectuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123

networks: 
  db-compose-network:
    driver: bridge