# Use root/example as user/password credentials
version: '3.1'

services:

  # server:
  #   container_name: NODE_APP_QUESTION_POOL
  #   command: npm run start:dev
  #   build: .
  #   ports:
  #     - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - mongo-express
  #   networks:
  #     - nest-network

  mongo:
    container_name: MONGO_DB_QUESTION_POOL
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - './.docker-data/mongo:/data/db'
      - ${PWD}/scripts/mongodb:/docker-entrypoint-initdb.d/
    networks:
      - nest-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - nest-network

networks:
  nest-network:
